title: "JAVA-Lehrgang mit GLOOP"
remote_theme: pmarsceill/just-the-docs
color_scheme: nil
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "JAVA-Lehrgang mit GLOOP":
    - "//github.com/budumlu/JAVA-Lehrgang-mit-GLOOP"
